# Generated by Django 5.2.3 on 2025-06-29 14:40

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0005_remove_chatgroup_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=120, unique=True),
        ),
    ]
