# Generated by Django 5.2.3 on 2025-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0012_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
